# Generated by Django 4.2.7 on 2023-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tarea_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=100, verbose_name='Hotel')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('pasajeros', models.IntegerField(verbose_name='PAX')),
                ('fecha_arribo', models.DateField(verbose_name='Fecha de Arribo')),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
