# Generated by Django 4.2.7 on 2023-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_reserva_delete_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hotel',
            field=models.CharField(max_length=120, verbose_name='Hotel'),
        ),
    ]
